config/routes.rb
Rails.application.routes.draw do
  resources :user
  root 'user#index'
  delete 'destroy_all_user', to: 'user#destroy_all_user'
  post 'make_list',to: 'user#make_list'
  post 'make_complete_list',to: 'user#make_complete_list'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name ,presence: :true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  require 'faker'
  before_action :set_user, only: %i[ show edit update destroy ]
  def index
    @users = User.all
  end

  def show
    @users = User.all
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to user_index_path, notice: " ✅ Argonaute ajouté ✅" }
        format.json { }
      else
        format.html { redirect_to user_index_path, alert: " 🚨 Argonaute non valide 🚨" }
        format.json { }
      end
    end
  end

  def destroy
      @user.destroy
  
      respond_to do |format|
        format.html { redirect_to user_index_path }
        format.js { }
      end
    end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.permit(:name)
  end

  def destroy_all_user
    User.destroy_all  
    respond_to do |format|
      format.html { redirect_to user_index_path, notice: " ✅ Liste supprimée ✅" }
      format.js { }
    end
  end

  def make_list
    9.times do
      u = User.create(name: Faker::Games::WorldOfWarcraft.hero.capitalize)
      end
      respond_to do |format|
        format.html { redirect_to user_index_path, notice: " ✅ Liste validée ✅" }
        format.js { }     
      end
  end

  def make_complete_list
    50.times do
      u = User.create(name: Faker::Games::LeagueOfLegends.champion.capitalize)
      end
      respond_to do |format|
        format.html { redirect_to user_index_path, notice: " ✅ Liste validée ✅" }
        format.js { }     
      end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_alert.html.erb
<p id="notice" class="text-center text-green"><%= notice %></p>
<p id="alert" class="text-center text-warning"><%= alert %></p>

app/views/layouts/_footer.html.erb
<div class="navbar fixed-bottom align-content-center" id="footer">
  <a href="https://github.com/KevinPiriou" target="about_blank" id="github" class="hover-fx"><i class="fab fa-github"></i></a>
  <p>Réalisé par Kévin Piriou pour Jason en Anthestérion de l'an 515 avant JC</p>
  <a href="https://www.linkedin.com/in/kevin-piriou/" target="about_blank" id="linkedin" class="hover-fx"><i class="fab fa-linkedin"></i></a>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light bg-dark" id="nav">
  <div class="m-1">
    <a class="navbar-brand" href="https://letmegooglethat.com/?q=Wild+Code+School"target="about_blank">
    <img src="https://www.wildcodeschool.com/assets/logo_main-e4f3f744c8e717f1b7df3858dce55a86c63d4766d5d9a7f454250145f097c2fe.png" width="160" height="50" class="" alt="">
    </a>
  </div>
  <div class="titre">
    <h1  id="nav-title">Les Argonautes</h1>
  </div>
  <div id="pill" onClick= themeChange()>
    <div id="ball">
      <span id="one" class="fa-solid fa-moon"></span>
      <span id="two" class="fa-solid fa-sun"></span>  
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Liste Argonaute</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/87a79565e0.js" crossorigin="anonymous"></script>
    <link href="http://fonts.cdnfonts.com/css/art-greco" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
<body id="bg">
  <%= yield %>
</body>
  <%= javascript_include_tag 'application' %>
</html>

app/views/user/index.html.erb
<%= render 'layouts/navbar' %>
<!-- Main section -->
<main>
  <!-- New member form -->
  <div class="main">
    <div class="card border-dark text-light text-center m-4 p-4 mx-4 mb-4 bg-primary rounded">
      <div class="fade-in-image">
        <%= image_tag 'Viking_Boat_clip_art.svg', alt:'viking boat'%>
      </div><% if User.all.length < 50 %>
      <h2 class="mt-5">Ajouter un(e) Argonaute</h2>
      <div class="form-group">
        <%= form_tag url_for(action: 'create'), method: "post" do %>
        <%= label_tag 'Nom'%>
		    <%= text_field_tag :name,"",id:'name', class: 'form-control input rounded', placeholder: 'Nom'%>
		    <br>
        <%= render 'layouts/alert' %>
        
        <div>
        <% end %>
          <% if User.all.length < 50 %>
          <%= submit_tag "AJOUTER A L'EQUIPAGE", class:"btn btn-outline-success text-light mt-2", id:"create"%>
          <% end %>
        </div>
      </div>
	    <% end %>
      <% if User.all.length < 50 %>
        <%= button_to 'EQUIPAGE ALEATOIRE DE 9 PERSONNES', make_list_url, class:"btn btn-outline-secondary mt-5 text-light" %>
        <%= button_to 'EQUIPAGE ALEATOIRE COMPLET (moche)', make_complete_list_url, class:"btn btn-outline-info mt-2 text-light" %>
      <% end %>
      </div>
      <!-- Member list -->
      <div class="card border-dark text-center m-4 p-4 mx-4 mb-4 mb-4 rounded" id="list" style="width: 70rem" >
        <% if User.all.length < 50 %>
        <h1>Membres de l'équipage actuel de l'Argo: <%= User.all.length %>/50</h1>
        <% else %>
        <h1 class="d-inline p-2 bg-danger text-white">COMPLET</h1>
        <% end %>
      <td><%= button_to '📛 SUPPRIMER LA LISTE 📛', destroy_all_user_path, class:"btn btn-danger" ,method: :delete %></td>
      <div class="d-flex flex-wrap justify-content-center">
        <% @users.each do |user| %>
          <div class="cardi m-2 p-2 text-light bg-dark border-info rounded-circle " style="width: 17.5rem;">
            <div class="center">
              <img src="https://img.icons8.com/external-others-maxicons/48/000000/external-spartan-greek-mythology-others-maxicons-4.png"/>
            </div><span class="badge badge-info">ARGONAUTE</span><br>
            <br><em class="text-success"> - <%= user.name.upcase%> - </em><br><br>
            <p class="text-muted">Ajouté le <%= user.created_at.strftime("%d %b") %></p>
            <td><%= button_to 'RETIRER', user, class:"btn btn-outline-danger",style:"margin:5px" ,method: :delete %></td>
          </div>
          <% end %>
      </div>
            
  </div>
</main>
<%= render 'layouts/footer' %>